<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZLaJhjv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZLaJhjv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZLaJhjv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZLaJhjv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZLaJhjv\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZLaJhjv',
    'container.build_id' => '984356ad',
    'container.build_time' => 1743503511,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZLaJhjv');
