<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNbMOxl6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNbMOxl6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNbMOxl6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNbMOxl6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNbMOxl6\App_KernelDevDebugContainer([
    'container.build_hash' => 'NbMOxl6',
    'container.build_id' => '0d158d57',
    'container.build_time' => 1743602224,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNbMOxl6');
