<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFrIPPd4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFrIPPd4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFrIPPd4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFrIPPd4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFrIPPd4\App_KernelDevDebugContainer([
    'container.build_hash' => 'FrIPPd4',
    'container.build_id' => 'ddb07868',
    'container.build_time' => 1743503373,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFrIPPd4');
